apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: three-tier
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: quotesdb  
  MYSQL_USER: user
  MYSQL_PASSWORD: password