apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: three-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: my-app-sa
      # 1. FIX KSV-0118 (Pod level): Forza l'esecuzione come utente non-root
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: frontend
        # Sostituisci <IL_TUO_USERNAME_DOCKERHUB> con il tuo username (es. oxiys)
        image: oxiys/three-tier-frontend:latest 
        # 2. FIX KSV-0118 (Container level) & KSV-0014: Disabilita privilegi e filesystem readonly
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 5002
        # Aggiunto per supportare readOnlyRootFilesystem (KSV-0014) senza far crashare l'app
        volumeMounts:
        - name: tmp-dir
          mountPath: /tmp
      # Volume temporaneo in memoria per i file di cache/temp
      volumes:
      - name: tmp-dir
        emptyDir: {}
